{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.clusterIssuer.name}}
spec:
{{- tpl (toYaml .Values.clusterIssuer.spec) . | nindent 2 }}
{{- end -}}