{{- if .Values.cloudflare.apiKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.apiKeySecretName }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiKey }}
{{- end -}}